baseURL="https://pesnik.github.io/sqa-notebook"
languageCode = "en-us"
title = "Software Quality Assurance Notebook"

theme = "cactus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
  description = "The intention is clear, preserving my sqa knowledge here which may help others to find things organized to start over their own sqa journey."
